development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: #{current_app_name}_development
  pool: 5
  username: root
  password: blank

test: &TEST
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: mysql
  encoding: utf8
  database: #{current_app_name}_production
  pool: 5
  username: root
  password:

staging:
  adapter: mysql
  encoding: utf8
  database: #{current_app_name}_staging
  pool: 5
  username: root
  password:

cucumber:
 <<: *TEST

